# these skeletons are defined in JARVIS format

jarvis23pt = {
    "Name": None,
    "Date of creation": None,
    "Recordings": {},
    "Cameras": [],
    "Entities": ["RodentBody"],
    "Keypoints": [
        "Snout",
        "Right_Ear",
        "Left_Ear",
        "Shoulder_Center",
        "Middle_Spine",
        "Hip_Center",
        "Tail_Root",
        "Tail_Middle",
        "Tail_Tip",
        "Right_Paw",
        "Right_Wrist",
        "Right_Elbow",
        "Right_Shoulder",
        "Left_Paw",
        "Left_Wrist",
        "Left_Elbow",
        "Left_Shoulder",
        "Right_Foot",
        "Right_Ankle",
        "Right_Knee",
        "Left_Foot",
        "Left_Ankle",
        "Left_Knee",
    ],
    "Skeleton": {
        "Joint 1": {"Keypoints": ["Snout", "Right_Ear"], "Length": [0]},
        "Joint 2": {"Keypoints": ["Snout", "Left_Ear"], "Length": [0]},
        "Joint 3": {"Keypoints": ["Right_Ear", "Shoulder_Center"], "Length": [0]},
        "Joint 4": {"Keypoints": ["Left_Ear", "Shoulder_Center"], "Length": [0]},
        "Joint 5": {"Keypoints": ["Right_Paw", "Right_Wrist"], "Length": [0]},
        "Joint 6": {"Keypoints": ["Right_Wrist", "Right_Elbow"], "Length": [0]},
        "Joint 7": {"Keypoints": ["Right_Elbow", "Right_Shoulder"], "Length": [0]},
        "Joint 8": {"Keypoints": ["Right_Shoulder", "Shoulder_Center"], "Length": [0]},
        "Joint 9": {"Keypoints": ["Left_Paw", "Left_Wrist"], "Length": [0]},
        "Joint 10": {"Keypoints": ["Left_Wrist", "Left_Elbow"], "Length": [0]},
        "Joint 11": {"Keypoints": ["Left_Elbow", "Left_Shoulder"], "Length": [0]},
        "Joint 12": {"Keypoints": ["Left_Shoulder", "Shoulder_Center"], "Length": [0]},
        "Joint 14": {"Keypoints": ["Right_Foot", "Right_Ankle"], "Length": [0]},
        "Joint 15": {"Keypoints": ["Right_Ankle", "Right_Knee"], "Length": [0]},
        "Joint 16": {"Keypoints": ["Right_Knee", "Hip_Center"], "Length": [0]},
        "Joint 17": {"Keypoints": ["Left_Foot", "Left_Ankle"], "Length": [0]},
        "Joint 18": {"Keypoints": ["Left_Ankle", "Left_Knee"], "Length": [0]},
        "Joint 19": {"Keypoints": ["Left_Knee", "Hip_Center"], "Length": [0]},
        "Joint 20": {"Keypoints": ["Tail_Root", "Hip_Center"], "Length": [0]},
        "Joint 21": {"Keypoints": ["Hip_Center", "Middle_Spine"], "Length": [0]},
        "Joint 22": {"Keypoints": ["Shoulder_Center", "Middle_Spine"], "Length": [0]},
    },
}


weinreb15pt = {
    "Name": None,
    "Date of creation": None,
    "Recordings": {},
    "Cameras": [],
    "Entities": ["RodentBody"],
    "Keypoints": [
        "tail_tip",
        "tail_base",
        "spine_low",
        "spine_mid",
        "spine_high",
        "left_ear",
        "right_ear",
        "forehead",
        "nose_tip",
        "left_hind_paw_front",
        "left_hind_paw_back",
        "right_hind_paw_front",
        "right_hind_paw_back",
        "left_fore_paw",
        "right_fore_paw",
    ],
    "Skeleton": {
        "Joint 1": {"Keypoints": ["nose_tip", "forehead"], "Length": [0]},
        "Joint 2": {"Keypoints": ["nose_tip", "left_ear"], "Length": [0]},
        "Joint 3": {"Keypoints": ["nose_tip", "right_ear"], "Length": [0]},
        "Joint 4": {"Keypoints": ["forehead", "spine_high"], "Length": [0]},
        "Joint 5": {"Keypoints": ["spine_high", "spine_mid"], "Length": [0]},
        "Joint 6": {"Keypoints": ["spine_mid", "spine_low"], "Length": [0]},
        "Joint 7": {"Keypoints": ["spine_low", "tail_base"], "Length": [0]},
        "Joint 8": {"Keypoints": ["tail_base", "tail_tip"], "Length": [0]},
        "Joint 9": {"Keypoints": ["left_fore_paw", "spine_high"], "Length": [0]},
        "Joint 10": {"Keypoints": ["right_fore_paw", "spine_high"], "Length": [0]},
        "Joint 11": {"Keypoints": ["left_hind_paw_back", "spine_low"], "Length": [0]},
        "Joint 12": {"Keypoints": ["right_hind_paw_back", "spine_low"], "Length": [0]},
        "Joint 13": {"Keypoints": ["left_hind_paw_front", "left_hind_paw_back"], "Length": [0]},
        "Joint 14": {"Keypoints": ["right_hind_paw_front", "right_hind_paw_back"], "Length": [0]},

    },
}


sainburg25pt = {'Name': None,
 'Date of creation': None,
 'Recordings': {},
 'Cameras': [],
 'Entities': ['RodentBody'],
 'Keypoints': ['tail_base',
  'spine_low',
  'spine_mid',
  'spine_high',
  'left_ear',
  'right_ear',
  'left_eye',
  'right_eye',
  'throat',
  'forehead',
  'nose_tip',
  'left_hind_paw_front',
  'left_hind_paw_back',
  'left_knee',
  'right_hind_paw_front',
  'right_hind_paw_back',
  'right_knee',
  'left_fore_paw',
  'left_wrist',
  'left_elbow',
  'left_shoulder',
  'right_fore_paw',
  'right_wrist',
  'right_elbow',
  'right_shoulder'],
 'Skeleton': {'Joint 1': {'Keypoints': ['tail_base', 'spine_low'],
   'Length': [0]},
  'Joint 2': {'Keypoints': ['spine_low', 'spine_mid'], 'Length': [0]},
  'Joint 3': {'Keypoints': ['spine_mid', 'spine_high'], 'Length': [0]},
  'Joint 4': {'Keypoints': ['spine_high', 'left_shoulder'], 'Length': [0]},
  'Joint 5': {'Keypoints': ['spine_high', 'right_shoulder'], 'Length': [0]},
  'Joint 6': {'Keypoints': ['left_ear', 'forehead'], 'Length': [0]},
  'Joint 7': {'Keypoints': ['right_ear', 'forehead'], 'Length': [0]},
  'Joint 8': {'Keypoints': ['left_eye', 'forehead'], 'Length': [0]},
  'Joint 9': {'Keypoints': ['right_eye', 'forehead'], 'Length': [0]},
  'Joint 10': {'Keypoints': ['spine_high', 'forehead'], 'Length': [0]},
  'Joint 11': {'Keypoints': ['forehead', 'nose_tip'], 'Length': [0]},
  'Joint 12': {'Keypoints': ['throat', 'nose_tip'], 'Length': [0]},
  'Joint 13': {'Keypoints': ['spine_high', 'throat'], 'Length': [0]},
  'Joint 14': {'Keypoints': ['left_hind_paw_front', 'left_hind_paw_back'],
   'Length': [0]},
  'Joint 15': {'Keypoints': ['left_hind_paw_back', 'left_knee'],
   'Length': [0]},
  'Joint 16': {'Keypoints': ['spine_low', 'left_knee'], 'Length': [0]},
  'Joint 17': {'Keypoints': ['right_hind_paw_front', 'right_hind_paw_back'],
   'Length': [0]},
  'Joint 18': {'Keypoints': ['right_hind_paw_back', 'right_knee'],
   'Length': [0]},
  'Joint 19': {'Keypoints': ['spine_low', 'right_knee'], 'Length': [0]},
  'Joint 20': {'Keypoints': ['left_fore_paw', 'left_wrist'], 'Length': [0]},
  'Joint 21': {'Keypoints': ['left_wrist', 'left_elbow'], 'Length': [0]},
  'Joint 22': {'Keypoints': ['left_elbow', 'left_shoulder'], 'Length': [0]},
  'Joint 23': {'Keypoints': ['right_fore_paw', 'right_wrist'], 'Length': [0]},
  'Joint 24': {'Keypoints': ['right_wrist', 'right_elbow'], 'Length': [0]},
  'Joint 25': {'Keypoints': ['right_elbow', 'right_shoulder'], 'Length': [0]}}}
